title:            Jaan
titlehilight:     Altosaar
tagline:          Excursions into Entropy.
description:      Physics PhD student at Princeton University. 
logo:             site-logo.png
#Comment out url when working locally to resolve base urls correctly
url: https://jaan.io

# Owner/author information
owner:
  name:           Jaan Altosaar
#  avatar:         avatar.png
  bio:            "Estonian-Canadian"
  email:          jaan@jaan.io
#  twitter:        ctrunsthis        
  github:         altosaar       
#  instagram:      ctrunsthis     
#  dribbble:       coletownsend
#  disqus:         balzac
  # Plug in your disqus shortname!
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
  google_analytics:   
  google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
  bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles 

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks -- was /:categories/:title
permalink:   /:title.html

#include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]